//
// Created by Acer on 2020/1/8.
//

#ifndef WYWONDERFULPLAYER_ERRORTYPE_H
#define WYWONDERFULPLAYER_ERRORTYPE_H
#define PREPARE_ERROR_HEAD 1000
#define PLAY_ERROR_HEAD 2000
enum ErrorType{
    OPEN_FAIL = PREPARE_ERROR_HEAD + 1   //打开文件失败
};

#endif //WYWONDERFULPLAYER_ERRORTYPE_H
